#CI
name: CI/Release Workflow

on: 
  push:
    branch:
      - '*'

env:
  DOCKER_REGISTRY: "dockerhub or jfrog"
  IMAGE_NAME: "dockerhub/anshuman"
  PRISMA_USER: ${{  secrets.PRISMA_USER  }}
  PRISMA_PASSWORD: ${{  secrests.PRISMA_PASSWORD  }}

jobs:
  build_and_push:
    name: Build, Test, and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: action/setup-java@v1
        with:
          java-version: 17

      - name: Build with maven
        run: mvn clean package

      - name: Generate short SHA
        uses: benjlevesque/short-sha@1.2
        id: short-sha
        with:
          length: 7

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to JFrog
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.JFROG_USERNAME  }}
          password: ${{  secrests.API_KEY  }}
          registry: ${{  env.DOCKER_RESGISTRY  }}

      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ${{  env.IMAGE_NAME  }}:${{  steps.short-sha.outputs.sha  }}
            ${{  env.IMAGE_NAME  }}:latest
          cache-from: type=registry,ref=${{  env.IMAGE_NAME  }}
          cache-to: type=inline
          load: true

      - id: scan-docker-image
        name: Scan docker image
        run: |
          curl -u $PRISMA_USER:$PRISMA_PASSWORD --output twistcli https://us-east1.cloud.twistclock.com/us-2-xxxxx/api/v1/util/twistcli && chmod +x twistcli && mv twistcli /tmp/
          /tmp/twistcli images scan --details --address https://us-east1.cloud.twistclock.com/us-2-xxxxx --user $PRISMA_USER --password $PRISMA_PASSWORD $IMAGE_NAME

      - if: github.ref == 'refs/heads/main'
        id: version-bump-git-tag
        name: Bump version and push git tag
        uses: anothrNick/github-tag-action@9885a4f9af
        env:
          GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN  }}

      - if: github.ref == 'refs/heads/main'
        name: Docker Push
        id: push-docker-image
        run: | 
          docker tag $IMAGE_NAME:${{  steps.short-sha.output.sha  }} $IMAGE_NAME:${{  steps.version-bump-git-tag.output.new_tag  }}
          docker push -a $IMAGE_NAME 

      - if: github.ref == 'refs/heads/main'
        name: Create Prerelease
        uses: ncipollo/release-actions@v1
        with:
          prerelease: true
          tag: ${{  steps.version-bump-git-tag.output.new_tag  }}
          token: ${{  secrets.GITHUB_TOKEN  }}